//////////////////////General Server Startup/////////////////////////////////////////
var express = require('express');
var app = express();
var path = require('path');
var bodyParser = require('body-parser');
var bpJason = bodyParser.json();
var urlencodedParser = bodyParser.urlencoded( { extended: false } );
var port = process.env.PORT || 9000;
var pg = require('pg');
var connectionString = 'postgress://localhost:5432/OWBS';


// using SendGrid's v3 Node.js Library
// https://github.com/sendgrid/sendgrid-nodejs
var helper = require('sendgrid').mail;


if(process.env.DATABASE_URL !== undefined) {
    console.log('env connection string');
    connectionString = process.env.DATABASE_URL;
    pg.defaults.ssl = true;
} else {
    connectionString = 'postgres://localhost:5432/OWBS';
}



// use public,bodyParserJson,urlencodedParser
app.use(express.static('public'));
app.use(urlencodedParser);
app.use(bpJason);

// spin up server
app.listen(port, function(){
  console.log('listening on port:', port);
});//End: General Server Startup


////////////////////////////////////////////////////////////////// GET ROUTES //////////////////////////////////////////////////////////////////////////////
/////////////////////Get Route: getJobPostings in DB///////////////////////////
app.get('/getJobPostings', function(req, res){
  console.log('in getJobPostings route');

  pg.connect(connectionString, function (err, client, done){
    if(err){
      console.log(err);
    } else{
      console.log('connected via getJobPostings');
      var existingJobPostingsArray = [];
      var queryResults = client.query('select * FROM jobPostings ORDER BY lower(jobposting_name);');
      queryResults.on('row', function(row){
        existingJobPostingsArray.push(row);
      });
      queryResults.on('end', function(){
        done();
        return res.json(existingJobPostingsArray);
      }); // end queryResults
    } //end else
  }); //end pg.connect
}); //end getJobPostings
//.................End Get Route: getJobPostings in DB.......................//


////////////////////////////////////////////////////////////////// POST ROUTES //////////////////////////////////////////////////////////////////////////////
/////////////////////POST Route: newJobPosting in DB///////////////////////////
app.post('/newJobPosting', function(req, res){
  console.log('in newJobPosting route req.body', req.body);

    var jobPostingName = req.body.jobPostingName;
    var jobPostingDescription = req.body.jobPostingDescription;
    var jobPostingOpen = req.body.jobPostingOpen;
    var jobPostingStart = 'now()';

  pg.connect(connectionString, function (err, client, done){
    if(err){
      console.log(err);
    } else{

      //array to hold results
      var newJobPostingsArray = [];

      client.query('INSERT INTO jobpostings (jobposting_name, jobposting_description, jobposting_open, jobposting_start) VALUES ($1, $2, $3, $4);', [jobPostingName, jobPostingDescription, jobPostingOpen, jobPostingStart]);

      var queryResults = client.query('select * FROM jobPostings ORDER BY lower(jobposting_name);');
      queryResults.on('row', function(row){
        newJobPostingsArray.push(row);
      });
      queryResults.on('end', function(){
        done();
        return res.json(newJobPostingsArray);
      }); // end queryResults
    } //end else
  }); //end pg.connect
}); //end getJobPostings
//.................End Put Route: modifyJobStatus in DB.......................//

////////////////////////////////////////////////////////////////// PUT ROUTES //////////////////////////////////////////////////////////////////////////////
/////////////////////Put Route: modifyJobStatus in DB///////////////////////////
app.put('/modifyJobStatus', function(req, res){
  console.log('in modifyJobStatus route req.body', req.body);

    var jobPostingID = req.body.jobPostingID;
    var jobPostingName = req.body.jobPostingName;
    var jobPostingDescription = req.body.jobPostingDescription;
    var jobPostingOpen = req.body.jobPostingOpen;
    var jobPostingStart = req.body.jobPostingStart;

  pg.connect(connectionString, function (err, client, done){
    if(err){
      console.log(err);
    } else{

      //array to hold results
      var newJobPostingsArray = [];

      client.query('UPDATE jobpostings SET jobposting_name = ($1), jobposting_description = ($2), jobposting_open = ($3), jobPosting_start = ($4) WHERE jobposting_id = ($5)', [jobPostingName, jobPostingDescription, jobPostingOpen, jobPostingStart, jobPostingID]);

      var queryResults = client.query('select * FROM jobPostings ORDER BY lower(jobposting_name);');
      queryResults.on('row', function(row){
        newJobPostingsArray.push(row);
      });
      queryResults.on('end', function(){
        done();
        return res.json(newJobPostingsArray);
      }); // end queryResults
    } //end else
  }); //end pg.connect
}); //end getJobPostings
//.................End Put Route: modifyJobStatus in DB.......................//

/////////////////////Put Route: modifyJobStatus in DB///////////////////////////
app.put('/checkCredentials', function(req, res){
  console.log('in checkCredentials route req.body', req.body);

    var userName = req.body.userName;
    var userPassword = req.body.userPassword;

  pg.connect(connectionString, function (err, client, done){
    if(err){
      console.log(err);
    } else{

      // //array to hold results
      var responseFromDB = [];

      var queryResults = client.query('SELECT * FROM adminLogin WHERE admin_username = ($1) AND admin_password = ($2)', [userName, userPassword]);

      // var queryResults = client.query('SELECT admin_username FROM adminLogin;');
      queryResults.on('row', function(row){
        responseFromDB.push(row);
        // responseFromDB = 'Successful Login';
        if(responseFromDB.length === 1){
          responseFromDB = 'AWESOME';
        }
      });
      queryResults.on('end', function(){
        done();
        return res.json(responseFromDB);
      }); // end queryResults
    } //end else
  }); //end pg.connect
}); //end getJobPostings
//.................End Put Route: modifyJobStatus in DB.......................//



////////////////////////////////////////////////////////////////// DELETE ROUTES //////////////////////////////////////////////////////////////////////////////
/////////////////////Put Route: deleteJob in DB///////////////////////////
app.delete('/deleteJob', function(req, res){
  console.log('in deleteJob route req.body', req.query.q);

    var jobPostingID = req.query.q;

  pg.connect(connectionString, function (err, client, done){
    if(err){
      console.log(err);
    } else{

      //array to hold results
      var newJobPostingsArray = [];

      client.query('DELETE FROM jobpostings WHERE jobposting_id = ($1)', [jobPostingID]);

      var queryResults = client.query('select * FROM jobPostings ORDER BY lower(jobposting_name);');
      queryResults.on('row', function(row){
        newJobPostingsArray.push(row);
      });
      queryResults.on('end', function(){
        done();
        return res.json(newJobPostingsArray);
      }); // end queryResults
    } //end else
  }); //end pg.connect
}); //end getJobPostings
//.................End Put Route: deleteJob in DB.......................//

/////////////////////POST Route: newJobPosting in DB///////////////////////////
app.post('/testEmail', function(req, res){
  console.log('in testEmail route req.body', req.body);

  var applicantName = req.body.applicantName;
  var applicantEmail = req.body.applicantEmail;
  var fileToSend = req.body.base64File;

  var from_email = new helper.Email(applicantEmail);
  var to_email = new helper.Email("oconnor.justin.r@gmail.com");
  var subject = "Application from: " + applicantName;
  var content = new helper.Content("text/plain", "Hello! My name is " + applicantName + ". My application is attached to this email. Thank you!");

  attachment = new helper.Attachment();
  attachment.setContent('UEsDBBQABgAIAAAAIQBtiidLZgEAAFQFAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0lMtugzAQRfeV+g/I2wqcdFFVVUgWfSzbSE0/wLEH4tYv2c7r7ztAgqooAalJNkgwc+89A3hGk41WyQp8kNbkZJgNSAKGWyFNmZOv2Vv6SJIQmRFMWQM52UIgk/HtzWi2dRASVJuQk0WM7onSwBegWcisA4OVwnrNIt76kjrGf1gJ9H4weKDcmggmprHyIOPRCxRsqWLyusHHDQnKSfLc9FVROWHOKclZxDKtqvSozoMKHcKVEQd06Y4sQ2XdExbShbvTCd8OyoMEqavR6gJqPvB1eikgmTIf35nGBrq2XlBh+VKjKOse7gijLQrJodVXbs5bDiHgd9IqayuaSbNnP8kR4lZBuDxF49sfDzGi4BoAO+dehDXMP69G8ce8F6TA3BmbK7g8RmvdCxHx1EJzHZ7NUdt0RWLn1FsXcAv4f4y9P66VOsWBHfgou/+6NhGtz54Pqk0gQBzJpvVOHP8CAAD//wMAUEsDBBQABgAIAAAAIQDHwie8/wAAAN8CAAALAAgCX3JlbHMvLnJlbHMgogQCKKAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArJLNSgMxEIDvgu8Q5t7NtoqINNuLCL2JrA8wJtPd6OaHZKrt2xtF1IVlEexx/j6+SWa9ObhBvFLKNngFy6oGQV4HY32n4LG9W1yDyIze4BA8KThShk1zfrZ+oAG5DOXexiwKxWcFPXO8kTLrnhzmKkTypbILySGXMHUyon7BjuSqrq9k+s2AZsQUW6Mgbc0FiPYY6X9s6YjRIKPUIdEipjKd2JZdRIupI1Zggr4v6fzZURUyyGmhy78Lhd3OaroNeu/I85QXHZi8ITOvhDHOGS1PaTTu+JF5C8lI85Wes1md9sO437snj3aYeJfvWvUcqfsQkqOzbN4BAAD//wMAUEsDBBQABgAIAAAAIQATqj6H9gAAADEDAAAcAAgBd29yZC9fcmVscy9kb2N1bWVudC54bWwucmVscyCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKySy2rDMBBF94X+g5h9LTt9UELkbEoh29b9AEUeP6gsCc304b+vaEjr0GC68PJeMfeeQbPZfg5WvGOk3jsFRZaDQGd83btWwUv1eHUPgli7WlvvUMGIBNvy8mLzhFZzGqKuDyRSiiMFHXNYS0mmw0FT5gO69NL4OGhOMrYyaPOqW5SrPL+TcZoB5Umm2NUK4q6+BlGNAf+T7ZumN/jgzduAjs9UyA/cPyNzWo5SrI4tsoKJmaVEkOdBbpYEabzjSu8t/mL8WHMQt0tCcJqdAHzLg1nMMRRLMhCPFiefcdBz9atF6/9cw9E5IsiTQy+/AAAA//8DAFBLAwQUAAYACAAAACEAJk2iEmcCAAARBwAAEQAAAHdvcmQvZG9jdW1lbnQueG1spFVbb5swFH6ftP9A/Z5yKW0iVFKlV/VhUtV0z5NjDHgBH8s2Sbtfv2MghG1alTZRhH1u3/nOOdhcXr3Wlbfh2giQKQlPA+JxySATskjJ95f7yYx4xlKZ0QokT8kbN+Rq/vXL5TbJgDU1l9ZDCGmSrWIpKa1Vie8bVvKamtNaMA0GcnvKoPYhzwXj/hZ05kdBGLQ7pYFxYzDfDZUbakgPV8NhaDVlu20UBDOUhRww/mUEiks05qBralHUBUbodaMmiKmoFStRCfvmsC4GmE1KGi2THmMy8HAxCRJINnW1c4b3fDui/bKL0IeQ7EJu+5a39HzNKyQM0pRC7fv2WTQ0ljuQdwseFbtVYXzc0G813eKyBzyEftYF1VXH/H3EMDhgIg5iiDiEwp85d0zGL9/2c60ZNTc8/xhA9DeAKo4bzoOGRu3RxHFoj3I9YLmr5ANY/ZDHpZnjyCxLqvAE1ix5LCRouqqQEY7Mw6577rUmc7ziVpC9uVWhOk4U1fQxS8nZNL6PpvGCtFrLX63TTvsfahO8TrPnlARBeBPfTa8H1S3PaVNZZ7m7CKPFos2i3cPOX0phPPz/bIz1qGe5sScnl74zuWfrtQJYu/tqaam2iCowceDgJa2xgB8PcE3Zmvhj3zuZDZ5+C6Wc2XBmn/T/yS7R7rTTMA5nXTtUsfyFVjwgYRTFbd4S9+ezuEV2Dt+og7SA5ziMOxctitLuxRVYC/Verng+spacZhxvxGnUijmAHYlFY1uxT8egMqg1ijLe+bRq/DA9aOGKroTkT8IyZHl2sau+K7zddvP199+y+W8AAAD//wMAUEsDBBQABgAIAAAAIQBvKMq+EAYAAI0aAAAVAAAAd29yZC90aGVtZS90aGVtZTEueG1s7Fndbts2FL4fsHcgdO9atiX/BHUKW7bbrUlbNGm3XtISLbGhRIOkkxhFgT3BgAHdsJsBu9vFbgpsz9Rh6x5iJGXZpE2v6OICxdAYiPnzncOP55AfKev2neucgEvEOKZF32vc8j2AipgmuEj73pPzSa3rAS5gkUBCC9T3loh7d44//+w2PBIZyhGQ9gU/gn0vE2J+VK/zWDZDfovOUSH7ZpTlUMgqS+sJg1fSb07qTd9v13OICw8UMJduH85mOEbgXLn0jivnYyL/FYKrhpiwM+UaWRYam1w01Bdf8ogwcAlJ35PjJPTqHF0LDxDIhezoe77+8+rHt+trIyL22Bp2E/23slsZJBdNbcfS6dowCMKgPVj71wAidnHjzrg9bq/9aQCMYznTkouJDYe94ShcYQ1QWXT4HnVGrYaFN/y3dvCDUH0svAaVxWAHP5lEmxgaoLIYOmLSaUaBhdegstjewXf8wSjoWHgNygguLnbQfthuRdVs15AZJfec8F4YTDrNFXyDqhurq7QvxL61lsPnlE0kQCcXClwAsZyjGYwlLoIETxkGJzjN5MKbw4Jy2ew3/Ynfkv/VJ9AlHRF4hKBhXTbFfKdJ8QE8Zngu+t6X0qtnQJ4twF0qMhyvRt21uAeL1LR4+8t3f//0Dfjrt5/fvvrejecmfoSK9GsMi38bQJgGb354/cfvr9/8+O2fv75ywAcMTk34Oc4RBw/QFXhMczk5xwBoyt7P4jyD2LQYFCmHBVQ2DvRYxs9EP1hCAh24IbIj+ZRJqXAB7y6eW4TPMrYQ2AG8n+UW8JRSMqTMOaf7aiwzCosidQ/OFibuMYSXrrGjrTyPF3O55rHLZZQhi+YjIlMOU1QgAVQfvUDIYfYMYyuupzhmlNOZAM8wGELsDMk5nlqraWN0D+cyL0sXQZlvKzanT8GQEpf7Ebq0kXJ3QOJyiYgVxrtwIWDuZAxzYiJPoMhcJM+WLLYCzoXMdIoIBeMEce6yeciWFt37UmLcaT8ly9xGMoEvXMgTSKm1welFlMF87uSMi8zEfsEv5BKF4BEVThLU3iGqLvMgxWNfup9iZKX73Xv7iZQh9wJRPQvm2hKI2vtxSWYQaef1LU3PcfFOgd+S9vDDSfspLuKMujX3IKLuht5EzgcMO/fTtojvw21Ld0RZgj9+5R7BRfEIyc3igH4S7k/C/b8X7n37+fByvVFofY2vLuvaTb735j7DhJyJJUEnXGs7l9NLJrJRV7TR+kFhnsniajgLlzKoy4BR8RUW2VkG53KYhh4h5SvXKQdzyuXpoJudvlUHWeSnNClbG43q2VQaQLFpl6dL1S7PIlG2tjubh7C1e11L9cNyRUDZvg8JYzCbRMtBolM1voOEntlBWPQcLLrK/V4W+muVFbn/AFQ/a4RByUiuN0hQovJU2lfZPXim9wXTnnbTMb2e4nqYTFskjOVmkzCWYQYTtN184Fz3Nim16KlQ7NLodD9ErpWIbGkDKewauJJ7rhVKNzGc972ZvBfKYj6X/rjSTUjSou/FYhXo/6Isc8bFCPKshOmucv45FogBgnO51s00kGLDrdHsqDl+pOR6/scXOf1lJhnNZigWe1o2VdlXOnH23hCsKnQhSZ9lyRWYkgV7DGWgwk5DBTDBXKyjmWBmLO5NFLfkarUVrd/MNlsUknkGVyeKKeYlXJfXdIx5aKbbs7Lrq8lMU5WkG5+67zZSHYZo7jlA1Knp1o8Pd8gbrDa6b7EqpXtb63qV1u07JW5+IBjUNoNZ1BRjB7VNq03tgBcCY7j10tx3Rhz6NNheteqAqO6VurbzcoJOn8uVP5LX1QURXFNF1/IZIap+Vi6VQLdW6nItwILhvvfCDwdB1Ayjmt8Nx7WgFfi1bjho1QZh2GqMw4Y/GjZfyqCILG+E5dgT+TxDlqt3L7p95/1LXl2zb8U0r1N9D65rY/3+pdHc//4FYBmZF+3mpNfqDdu1XmswqQWjYbfWi9rD2qgddUaTURR2e5OXHrjU4GDQioL2uFtrN6KoFrR9Rb/bq3WCZnMQdAbdcTB4uYq1nHn1XYVX8zr+BwAA//8DAFBLAwQKAAAAAAAAACEA10fVLlAtAABQLQAAFwAAAGRvY1Byb3BzL3RodW1ibmFpbC5qcGVn/9j/4AAQSkZJRgABAQAASABIAAD/4QCARXhpZgAATU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAIdpAAQAAAABAAAATgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAYugAwAEAAAAAQAAAgAAAAAA/+0AOFBob3Rvc2hvcCAzLjAAOEJJTQQEAAAAAAAAOEJJTQQlAAAAAAAQ1B2M2Y8AsgTpgAmY7PhCfv/AABEIAgABiwMBEQACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/3QAEADL/2gAMAwEAAhEDEQA/AP7V/gl8EvgxN8GPhFNN8I/hhLLL8MPAMsssvgHwrJJLJJ4U0lnkkdtKLO7sSzuxLMxJJJJNAHp//Cjfgp/0R/4W/wDhvvCf/wAqaAD/AIUb8FP+iP8Awt/8N94T/wDlTQAf8KN+Cn/RH/hb/wCG+8J//KmgA/4Ub8FP+iP/AAt/8N94T/8AlTQAf8KN+Cn/AER/4W/+G+8J/wDypoAP+FG/BT/oj/wt/wDDfeE//lTQAf8ACjfgp/0R/wCFv/hvvCf/AMqaAD/hRvwU/wCiP/C3/wAN94T/APlTQAf8KN+Cn/RH/hb/AOG+8J//ACpoAP8AhRvwU/6I/wDC3/w33hP/AOVNAB/wo34Kf9Ef+Fv/AIb7wn/8qaAD/hRvwU/6I/8AC3/w33hP/wCVNAB/wo34Kf8ARH/hb/4b7wn/APKmgA/4Ub8FP+iP/C3/AMN94T/+VNAB/wAKN+Cn/RH/AIW/+G+8J/8AypoAP+FG/BT/AKI/8Lf/AA33hP8A+VNAB/wo34Kf9Ef+Fv8A4b7wn/8AKmgA/wCFG/BT/oj/AMLf/DfeE/8A5U0AH/Cjfgp/0R/4W/8AhvvCf/ypoAP+FG/BT/oj/wALf/DfeE//AJU0AH/Cjfgp/wBEf+Fv/hvvCf8A8qaAD/hRvwU/6I/8Lf8Aw33hP/5U0AH/AAo34Kf9Ef8Ahb/4b7wn/wDKmgA/4Ub8FP8Aoj/wt/8ADfeE/wD5U0AH/Cjfgp/0R/4W/wDhvvCf/wAqaAD/AIUb8FP+iP8Awt/8N94T/wDlTQAf8KN+Cn/RH/hb/wCG+8J//KmgA/4Ub8FP+iP/AAt/8N94T/8AlTQAf8KN+Cn/AER/4W/+G+8J/wDypoAP+FG/BT/oj/wt/wDDfeE//lTQAf8ACjfgp/0R/wCFv/hvvCf/AMqaAD/hRvwU/wCiP/C3/wAN94T/APlTQAf8KN+Cn/RH/hb/AOG+8J//ACpoAP8AhRvwU/6I/wDC3/w33hP/AOVNAB/wo34Kf9Ef+Fv/AIb7wn/8qaAD/hRvwU/6I/8AC3/w33hP/wCVNAB/wo34Kf8ARH/hb/4b7wn/APKmgA/4Ub8FP+iP/C3/AMN94T/+VNAB/wAKN+Cn/RH/AIW/+G+8J/8AypoAP+FG/BT/AKI/8Lf/AA33hP8A+VNAB/wo34Kf9Ef+Fv8A4b7wn/8AKmgA/wCFG/BT/oj/AMLf/DfeE/8A5U0AH/Cjfgp/0R/4W/8AhvvCf/ypoAP+FG/BT/oj/wALf/DfeE//AJU0AH/Cjfgp/wBEf+Fv/hvvCf8A8qaAD/hRvwU/6I/8Lf8Aw33hP/5U0AH/AAo34Kf9Ef8Ahb/4b7wn/wDKmgA/4Ub8FP8Aoj/wt/8ADfeE/wD5U0AfhP8AtlfCj4W2f7SPxHt7T4beAbW3j/4RDy4Lfwb4eghj3+A/C7vsii09UXc7s7bVGXZmOSxNAH//0P7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//R/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9L+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//0/7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//U/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9X+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAc/wCKvD9p4q8Oax4dvrjW7W11ayltJbjw34m8ReDddiDYZX0zxR4S1XRPEei3O9FC3mk6tYXSruQTiN3WgD8iPCXwZ/b8+G/g7wZD4Z1n4jeJL/U/gv8AArwb8RfDnj34v6V44v4/HVj8Ffi74g+KvjiP4jeLPH9/8QV8W2nx3j+GvhGGTQvHSeFrvw54m1j7Jo+taHpelaz4KAPoeVv239U+FWitJo+u6V8VNF+K3xlS41q5vvhPdNqHgpv2c/jLD8LvF9r8P/DnjPwt4OfRh8cNV+G2l6f8KfF3j7xrqNsbKHVfE/jzULOD/hNtGAKPib4jftXaf4j/AGWY9E+HPjDV/GUHwS1nxT+0T8NLXxJ8P9d1m2ubr4qfszaFPpk3iw3vwt+A+p+NH8Oz/GPU9F1CJfCwvrLwx4wPgO1so2utG1AA5T4Uj/goZrPjX4I33xnsfHuhaNo3jL4Zah8U4fCmrfs02XhPVtK1/wDZt+I9l8RdFvvDVpJ4g8Vy+GvAvx4sPBMuoa5pHj3Udc8Vv4zttQ8GeEPD+j+Er4WAB0mvS/t2eLvDn7aWkx+H/HXw9Wyl0qb9ljVtG8X/ALPOs+OvET6R8RviQviGLwbejSdP8MaBoviv4d+HfhffeGdH+NemS69od/4513TNe8eXlxZS3PhkAw9O1T/go6fEHie41nw9q58PR/tKeFNO8OaHpE/7O1pe3v7PZ8ZfGLS9U19fGF9qOrJo0Ufw8l+B3jHxjpOoeBPEnji88Y6P458JeBL/AEfSfHdlq/wjAJfg58K/2sRY/BfU/ip4h+L994p0fwF+x7pXxPuPE3i74aM2p+Nfhn4t/aWm+N+pT23w48V6X4XvtM1+28XfD6W5vLHw8mp+KvB1t4CXW4/EvizR/Eun+GwD9PKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/BP9tL/k5f4lf9yd/6gHhWgD//1v7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//X/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9D+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//0f7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//S/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9P+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//1P7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//V/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9b+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//1/7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//Q/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9H+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//0v7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//T/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9T+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//1f7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//W/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9f+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//0P7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//R/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9L+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//0/7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//U/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9X+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//1v7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//X/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9D+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//0f7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//S/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9P+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//1P7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//V/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9b+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//1/7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//Q/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9H+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//0v7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//T/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9T+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//1f7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//W/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9f+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//0P7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//R/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9L+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//0/7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//U/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9X+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//1v7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//X/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9D+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//0f7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//S/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9P+6b4G/wDJFPg//wBkt+H/AP6iekUAepUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB+Cf7aX/Jy/xK/7k7/1APCtAH//1P7pvgb/AMkU+D//AGS34f8A/qJ6RQB6lQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH4J/tpf8nL/Er/uTv/UA8K0Af//V/um+Bv8AyRT4P/8AZLfh/wD+onpFAHqVABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfgn+2l/ycv8Sv+5O/9QDwrQB//9b+1f4JfG34MQ/Bj4RQzfFz4YRSxfDDwDFLFL4+8KxyRSR+FNJV45EbVQyOjAq6MAysCCAQRQB6f/wvL4Kf9Fg+Fv8A4cHwn/8ALagA/wCF5fBT/osHwt/8OD4T/wDltQAf8Ly+Cn/RYPhb/wCHB8J//LagA/4Xl8FP+iwfC3/w4PhP/wCW1AB/wvL4Kf8ARYPhb/4cHwn/APLagA/4Xl8FP+iwfC3/AMOD4T/+W1AB/wALy+Cn/RYPhb/4cHwn/wDLagA/4Xl8FP8AosHwt/8ADg+E/wD5bUAH/C8vgp/0WD4W/wDhwfCf/wAtqAD/AIXl8FP+iwfC3/w4PhP/AOW1AB/wvL4Kf9Fg+Fv/AIcHwn/8tqAD/heXwU/6LB8Lf/Dg+E//AJbUAH/C8vgp/wBFg+Fv/hwfCf8A8tqAD/heXwU/6LB8Lf8Aw4PhP/5bUAH/AAvL4Kf9Fg+Fv/hwfCf/AMtqAD/heXwU/wCiwfC3/wAOD4T/APltQAf8Ly+Cn/RYPhb/AOHB8J//AC2oAP8AheXwU/6LB8Lf/Dg+E/8A5bUAH/C8vgp/0WD4W/8AhwfCf/y2oAP+F5fBT/osHwt/8OD4T/8AltQAf8Ly+Cn/AEWD4W/+HB8J/wDy2oAP+F5fBT/osHwt/wDDg+E//ltQAf8AC8vgp/0WD4W/+HB8J/8Ay2oAP+F5fBT/AKLB8Lf/AA4PhP8A+W1AB/wvL4Kf9Fg+Fv8A4cHwn/8ALagA/wCF5fBT/osHwt/8OD4T/wDltQAf8Ly+Cn/RYPhb/wCHB8J//LagA/4Xl8FP+iwfC3/w4PhP/wCW1AB/wvL4Kf8ARYPhb/4cHwn/APLagA/4Xl8FP+iwfC3/AMOD4T/+W1AB/wALy+Cn/RYPhb/4cHwn/wDLagA/4Xl8FP8AosHwt/8ADg+E/wD5bUAH/C8vgp/0WD4W/wDhwfCf/wAtqAD/AIXl8FP+iwfC3/w4PhP/AOW1AB/wvL4Kf9Fg+Fv/AIcHwn/8tqAD/heXwU/6LB8Lf/Dg+E//AJbUAH/C8vgp/wBFg+Fv/hwfCf8A8tqAD/heXwU/6LB8Lf8Aw4PhP/5bUAH/AAvL4Kf9Fg+Fv/hwfCf/AMtqAD/heXwU/wCiwfC3/wAOD4T/APltQAf8Ly+Cn/RYPhb/AOHB8J//AC2oAP8AheXwU/6LB8Lf/Dg+E/8A5bUAH/C8vgp/0WD4W/8AhwfCf/y2oAP+F5fBT/osHwt/8OD4T/8AltQAf8Ly+Cn/AEWD4W/+HB8J/wDy2oAP+F5fBT/osHwt/wDDg+E//ltQAf8AC8vgp/0WD4W/+HB8J/8Ay2oAP+F5fBT/AKLB8Lf/AA4PhP8A+W1AH4T/ALZXxX+Ft5+0j8R7i0+JPgG6t5P+EQ8ue38ZeHp4ZNngPwuj7JYtQZG2ujI21jh1ZTgqRQB//9kAAABQSwMEFAAGAAgAAAAhAFLt83G7AwAA7gkAABEAAAB3b3JkL3NldHRpbmdzLnhtbLRW227bOBB9X2D/wdDzKpZkyXGEOoUv8TZF3AaV+wGURNlEeBFIylp3sf++Q0qM3NYovFs0LxnNmSt5Zug3b/9idHTEUhHB5154E3gjzAtREr6fe593G3/mjZRGvERUcDz3Tlh5b+9//+1NmyqsNZipEYTgKmXF3DtoXafjsSoOmCF1I2rMAayEZEjDp9yPGZIvTe0XgtVIk5xQok/jKAimXh9GzL1G8rQP4TNSSKFEpY1LKqqKFLj/5zzkNXk7l7UoGoa5thnHElOoQXB1ILVy0dj/jQbgwQU5/qiJI6POrg2DK9pthSxfPa4pzzjUUhRYKbggRl2BhA+J4+8Cvea+gdx9izYUuIeBlc4rT/5bgOibAIpe00kHPZFcItnxpG+DFenjnguJcgqshHZGUJF3D7T8IgQbtWmNZQF3A5wOAm9sADgRUWUaaQywqjGlluQFxQgCtuleIgb0dBrrU+IKNVTvUJ5pUYPREUHdt1EfsjggiQqNZVajAqKtBNdSUGdXig9Cr4DqEm6i81DoiJ8lPhLcPpNCNxJ3gew8DFLWzRYE4ohBg1/Ny1aU2BTcSHL9HRgHWxQc01nKbxMJ2AWSlHhnDjbTJ4o30FNGvuAFL983ShOIaKfmJyr4UQGYm8wfgQq7U403GJkzUr8omb2gDSX1lkgp5CMvgTK/LBmpKiwhAQEKboFVRIrWnvM7jEpYwT+Zd3xOI1jopXLCJyG0Mw2Ch2kYLRZdpQYdkCCOF7PNJWQahGE0vYgk4TpZX0JuwzicxZeQ2QT8Hi4hd6skWV+sbah6/NodS83SfZZOMlQdsc5jhVguCRptzVoeG4tcviwJd3iOYc/gcyRrcgf6fgcohijdwIg7wM49S0ui6jWurEy3SO6HuL2FvKiFdfL+NZZZT1j+KUVTd2grUd1R0JmEcdx7Eq6fCHN61eSZ8+KwGc+ghpcfj9Ke03A8baqBSnaUn5ClpLXF3P+c9ZSlMjN0w1tU1x1r83049yjZH3RoiKbhq4TX237k+6jHIotFHWY/UGE6A+teGHSR053ZTZxuMuhip4sHXeJ0yaCbOt3U6A6wLyTs9BcYICcafSUoFS0u3w34dyq37QsCN56dWD4s8ZsOo0TBRNew77WQDvvDYmGclqJ4BLKC1D0Qi8ndejPpNq2Bu2fkkaE9XtdkMJxEt9Pbziqxr4neAdte4AI+4WqJFC57zCVIOr+/N+ZvFi39RbiO/HiaLP1ZtHrwl5toEa4Wd9NkFf3TT4v7oXb/LwAAAP//AwBQSwMEFAAGAAgAAAAhAPC8NQHcAQAA8QUAABIAAAB3b3JkL2ZvbnRUYWJsZS54bWy8k9tq4zAQhu8LfQej+8ay4vRg6pQ0bWBh6cXSfQBFkW2xOhhJiTdvvyPZcQMhbJallUHI/4x+jT40j0+/lUx23DphdImyCUYJ18xshK5L9PN9dXOPEuep3lBpNC/Rnjv0NL++euyKymjvEtivXaFYiRrv2yJNHWu4om5iWq4hWBmrqIdfW6eK2l/b9oYZ1VIv1kIKv08JxrdosLGXuJiqEoy/GLZVXPu4P7VcgqPRrhGtO7h1l7h1xm5aaxh3Du6sZO+nqNCjTZafGCnBrHGm8hO4zFBRtILtGY4rJT8MZv9mQEYDxYpvtTaWriXAh0oSMEPzgX7SFZoqCCypFGsrYqCl2jieQWxHZYkwwSs8gzl8OZ6GGaUhkTXUOh5M+kTcyxVVQu4PKt160+ut8Kw5yDtqRaipDzlRQ2Dr1rhErxgGWa1Qr2QlykFYLEeFhKPiyAZlOio4KCz69BkPcReLPmMOnJn2AE5AvAvFXfLGu+SHUVSfAULwLYCYAY4AZvr5QMji9QjIEpS7+/xw/Q8gD38H0mO8HMgCypJnMDwDhnx4GfF1fD6G43cxYJh+BYahQZLvom782TYJzfFFbbIIFZPjVxHahOC75xMc8fL/2SbDws3/AAAA//8DAFBLAwQUAAYACAAAACEA4IvKVR8BAAARAgAAFAAAAHdvcmQvd2ViU2V0dGluZ3MueG1slNFRS8MwEAfwd8HvUPK+pRs6tKwbgkz2MgbVD5Cl1zWY5EIua7dv71nnRHyZbzku9+P+3Hx5dDbrIJJBX4rJOBcZeI218ftSvL2uRg8io6R8rSx6KMUJSCwXtzfzvuhhV0FK/JMyVjwVTpeiTSkUUpJuwSkaYwDPzQajU4nLuJdOxfdDGGl0QSWzM9akk5zm+UycmXiNgk1jNDyjPjjwaZiXESyL6Kk1gb61/hqtx1iHiBqIOI+zX55Txl+Yyd0fyBkdkbBJYw5z3migeHySDy9nf4D7/wHTC+B0sd57jGpn+QS8ScaYWPANlLXYbzcv8rOocYOpUh08UcUpLKyMhaETzBEsbSGuvW6zvuiULcXjTHBT/jrk4gMAAP//AwBQSwMEFAAGAAgAAAAhAEswtnpzAQAA9QIAABEACAFkb2NQcm9wcy9jb3JlLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIySwU7DMAxA70j8Q5ULpy7NigBVXScB4oCYQGIIxC0k3hZokyjx6Pb3pO3WUbEDNzt+fnWd5NNNVUbf4LwyekLYKCERaGGk0ssJeZnfxVck8si15KXRMCFb8GRanJ7kwmbCOHhyxoJDBT4KJu0zYSdkhWgzSr1YQcX9KBA6FBfGVRxD6pbUcvHFl0DHSXJBK0AuOXLaCGPbG8lOKUWvtGtXtgIpKJRQgUZP2YjRA4vgKn+0oa38IiuFWwtH0X2xpzde9WBd16M6bdEwP6Nvs4fn9ldjpZtdCSBFLkWGCksocnoIQ+TXH58gsDvukxALBxyNK+7XHpWOHs9ujNbGtdy+1mz9C7a1cdIHwyALmAQvnLIY7rLzDw4CXXKPs3C5CwXyevv3U3+RpsvBt2reR8Faok/z3bK78UBGYUlZt9J95TW9uZ3fkWKcsMs4SWOWzscsY2mWJO/NhIP+g7DaDfB/4/nQuBd0Sxo+1OIHAAD//wMAUEsDBBQABgAIAAAAIQCbi+1VKQsAAKtyAAAPAAAAd29yZC9zdHlsZXMueG1svJ1bV+M4Esff95z9Dj55mn3ohnDt5gw9B+hm4Sz0MBN6+1mxFaJFtrK+cNlPv7LsJAplOS6phifIpX6S9de/pLLj5NffXlIZPfG8ECo7HY0/7o4insUqEdnD6ejH/eWHT6OoKFmWMKkyfjp65cXoty9//9uvzydF+Sp5EWlAVpyk8eloXpaLk52dIp7zlBUf1YJn+sWZylNW6of5w07K8sdq8SFW6YKVYiqkKF939nZ3j0YtJh9CUbOZiPlXFVcpz0oTv5NzqYkqK+ZiUSxpz0NozypPFrmKeVHog05lw0uZyFaY8QEApSLOVaFm5Ud9MG2PDEqHj3fNf6lcAw5xgL0VII1Prh8ylbOp1KOvexJp2OiLHv5ExV/5jFWyLOqH+V3ePmwfmT+XKiuL6PmEFbEQ97plDUmF5l2dZYUY6Vc4K8qzQrDOF+f1P52vxEVpPX0uEjHaqVss/qdffGLydLR3sHzmou7BxnOSZQ/L53j24cfE7on11FRzT0cs/zA5qwN32gNr/lqHu1g9at71Zmz01NATZdLMV/0qn92o+JEnk1K/cDrarZvST/64vsuFyvWcPB19/tw+OeGpuBJJwjPrjdlcJPznnGc/Cp6sn//j0syr9olYVZn+f//T2Ogli+TbS8wX9SzVr2asHr3vdYCs312JdeMm/L9L2Lgds674OWe1VaPxW4TpPgqxV0cU1tF2M6s3x27ehWpo/70aOnivhg7fq6Gj92ro+L0a+vReDRnMX9mQyBL+0hgRNgOo2zgON6I5DrOhOQ4voTkOq6A5DiegOY6JjuY45jGa45imCE6pYtcstCb7vmO293O3rxF+3O1Lgh93+wrgx92e8P242/O7H3d7Ovfjbs/eftztyRrPbbZa0bW2WVYGu2ymVJmpkkclfwmnsUyzTP1Cw6sXPZ6THCQBpsls7UIcTIuZebx9hhiT+q/nZV1yRWoWzcRDleuyN7TjPHviUhegEUsSzSME5ryscseI+MzpnM94zrOYU05sOqgUGY+yKp0SzM0FeyBj8SwhHr4lkSQprCY0q8p5bRJBMKlTFucqvGuKkeWHG1GEj1UNic4rKTkR6zvNFDOs8NrAYMJLA4MJrwwMJrwwsDSjGqKWRjRSLY1owFoa0bg185Nq3Foa0bi1NKJxa2nh43YvSmlSvL3rGA8/d3chVX3GObgfE/GQMb0BCF9u2nOm0R3L2UPOFvOoPn/cjbWPGdvOuUpeo3uKNW1FotrXmylyoY9aZFX4gG7QqMy14hHZa8UjMtiKF26xW71NrjdoVzT1zKSalp2mNaRBpp0wWTUb2nC3sTJ8hq0NcCnygswG3ViCGfy93s7WclJkvnUvwzu2ZoXb6m1WIu1eiyTopVTxI00avnpd8FyXZY/BpEslpXrmCR1xUuaqmWu25feMJIMs/y1dzFkhTK20gRi+1C+vVUe3bBF8QHeSiYxGt28fUiZkRLeDuLq/vYnu1aIuM+uBoQGeq7JUKRmzPRP4y08+/QdNB890EZy9Eh3tGdHpIQO7EASLTENSCRFJbzNFJkjWUMP7F3+dKpYnNLS7nDcfDyk5EXHC0kWz6SDwls6Lzzr/EOyGDO/fLBf1eSEqU92TwKzThkU1/Q+Pw1PddxWRnBn6vSrN+Uez1TXRdLjwbcIGLnyLYNTUy0M9fwkOdgMXfrAbOKqDvZCsKITzEqo3j+pwlzzq4w0v/lqekiqfVZJuAJdAshFcAsmGUMkqzQrKIzY8wgM2POrjJZwyhkdwSs7w/pmLhEwMA6NSwsCoZDAwKg0MjFSA8E/oWLDwj+lYsPDP6jQwoi2ABaOaZ6TLP9FVHgtGNc8MjGqeGRjVPDMwqnm2/zXis5neBNMtMRaSas5ZSLqFJit5ulA5y1+JkN8kf2AEJ0gb2l2uZvV9AyprPsRNgKzPUUvCzXaDoxL5J5+Sda1mUfaL4Iwok1IponNr6wXHRG5+dm1bmLnnIrgL5mT7DX/iFLtxC0Z0GaCBhctmwcKXKQsWvkxZsPBlyoKFL1MWLHyZsmDhn1++kyzmcyUTnjuM2NeRaLJgcXttCVyjHnSu/kY8zMtoMl9dorIxR7tbI5dnmTbCtjfYlSiO9nrCbnkiqnTZUXgH0NH+8GBj6I3g5Y1aPcHr7e9G5OHASNjm0fbIdWm3EXk8MBK2+WlgpMlSG5F9Sfwryx87J8Jx3/xZnZhwTL7jvlm0Cu5stm8irSK7puBx3yzasEp0Fsf1JS6ozjDPuOOHmccdj3GRm4Kxk5sy2FduRJ/B/uRPot6OYpKmaW/1kZ+3ze2bJXVQ5vyjUs3Fpo2rpMPvRLzWu/2s4FEnZ3/41daNLOMex8Hpxo0YnHfciMEJyI0YlImc4aiU5KYMzk1uxOAk5UagsxVcEXDZCsbjshWM98lWkOKTrQJ2AW7E4O2AG4E2KkSgjRqwU3AjUEYF4V5GhRS0USECbVSIQBsVbsBwRoXxOKPCeB+jQoqPUSEFbVSIQBsVItBGhQi0USECbVTPvb0z3MuokII2KkSgjQoRaKOa/WKAUWE8zqgw3seokOJjVEhBGxUi0EaFCLRRIQJtVIhAGxUiUEYF4V5GhRS0USECbVSIQBu1uT/W36gwHmdUGO9jVEjxMSqkoI0KEWijQgTaqBCBNipEoI0KESijgnAvo0IK2qgQgTYqRKCNai4dBBgVxuOMCuN9jAopPkaFFLRRIQJtVIhAGxUi0EaFCLRRIQJlVBDuZVRIQRsVItBGhYi++dleV3fdGzLGn/V03mYy/NJV26k/7e8fsFH7w1HLXrlZw2+gOVfqMeq8W3bf1BvDIGIqhTKnqB2fBbG55gIp6mr97xf9t6XZ9MBvCmtv4DEX+gH8YGgkOKdy0Dfl7UhQ5B30zXQ7Euw6D/qyrx0JlsGDvqRrfLn8JJVejkBwX5qxgseO8L5sbYXDIe7L0VYgHOG+zGwFwgHuy8dW4GFUJ+e30YcDx+lo9aFoQOibjhbh2E3om5ZQq2U6hsYYKpqbMFQ9N2GojG4CSk8nBi+sG4VW2I3ykxraDCu1v1HdBKzUkOAlNcD4Sw1R3lJDlJ/UMDFipYYErNT+ydlN8JIaYPylhihvqSHKT2q4lGGlhgSs1JCAlTpwQXZi/KWGKG+pIcpPari5w0oNCVipIQErNSR4SQ0w/lJDlLfUEOUnNaiS0VJDAlZqSMBKDQleUgOMv9QQ5S01RPVJbc6ibEiNUtgKx23CrEDcgmwF4pKzFehRLVnRntWSRfCslqBWS81x1ZItmpswVD03YaiMbgJKTycGL6wbhVbYjfKTGlctdUntb1Q3ASs1rlpySo2rlnqlxlVLvVLjqiW31LhqqUtqXLXUJbV/cnYTvKTGVUu9UuOqpV6pcdWSW2pctdQlNa5a6pIaVy11SR24IDsx/lLjqqVeqXHVkltqXLXUJTWuWuqSGlctdUmNq5acUuOqpV6pcdVSr9S4asktNa5a6pIaVy11SY2rlrqkxlVLTqlx1VKv1LhqqVdqXLV0q0ME5nvLdp43fn2sBpvfzdPvL18XvP4CeuvGm6T5At4WaN54nax+JawOrrsRtb+c1j5tetteeGxaNIGwqXiu24rbrw5zNNV+BfDqdiDzBcBvG3Z8T7DpyHool+9upVmPV/O+jdHq7XdZS9fTZyNt7xg16rs6+Lmdztt6qPszlc0P6+l/rrNEA57bX2trepq8sAalX7/gUt6y5t1q4X6r5LOyeXW8a27FffP6tPnyQ2d8bhKOE7Cz2ZnmYfsjeo7xbn4Oob0S7pyStas6htt8LCN0pNd9W/5XfPk/AAAA//8DAFBLAwQUAAYACAAAACEAGx+NBWkBAAC3AgAAEAAIAWRvY1Byb3BzL2FwcC54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACcUsFKxTAQvAv+Q+ndl1ZRVPZFRBEPKsKrz3NItm0wTUKyiu/v3VqtFW/mtDObzO4MgYv3wRVvmLINfl3Wq6os0OtgrO/W5VNzc3BaFpmUN8oFj+tyh7m8kPt78JhCxEQWc8ESPq/LniieC5F1j4PKK2577rQhDYoYpk6EtrUar4N+HdCTOKyqE4HvhN6gOYizYDkpnr/Rf0VN0ON+edvsIutJaHCIThHKh/GlW5lAA4iZhSaQco0dUNZMzwAeVYd55KYCnkMyWR6BmAq46lVSmjg/WZ+BWEC4jNFZrYiDlfdWp5BDS8W90tZTyH0xKoBY3gI2sUH9miztZAViCeHO+mmTqeDNkuqSiv3XejOCjVYOr9i+bJXLCOKHGFVe8lNswvVo+6v/m1x4erbUb6LSPO+wXrpbNGDDLBredR43E3DL8Sc3yvNb36H5vvO3Mea1nf6hrI9XFZ/PdL459jh/EPkBAAD//wMAUEsBAi0AFAAGAAgAAAAhAG2KJ0tmAQAAVAUAABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAx8InvP8AAADfAgAACwAAAAAAAAAAAAAAAACfAwAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEAE6o+h/YAAAAxAwAAHAAAAAAAAAAAAAAAAADPBgAAd29yZC9fcmVscy9kb2N1bWVudC54bWwucmVsc1BLAQItABQABgAIAAAAIQAmTaISZwIAABEHAAARAAAAAAAAAAAAAAAAAAcJAAB3b3JkL2RvY3VtZW50LnhtbFBLAQItABQABgAIAAAAIQBvKMq+EAYAAI0aAAAVAAAAAAAAAAAAAAAAAJ0LAAB3b3JkL3RoZW1lL3RoZW1lMS54bWxQSwECLQAKAAAAAAAAACEA10fVLlAtAABQLQAAFwAAAAAAAAAAAAAAAADgEQAAZG9jUHJvcHMvdGh1bWJuYWlsLmpwZWdQSwECLQAUAAYACAAAACEAUu3zcbsDAADuCQAAEQAAAAAAAAAAAAAAAABlPwAAd29yZC9zZXR0aW5ncy54bWxQSwECLQAUAAYACAAAACEA8Lw1AdwBAADxBQAAEgAAAAAAAAAAAAAAAABPQwAAd29yZC9mb250VGFibGUueG1sUEsBAi0AFAAGAAgAAAAhAOCLylUfAQAAEQIAABQAAAAAAAAAAAAAAAAAW0UAAHdvcmQvd2ViU2V0dGluZ3MueG1sUEsBAi0AFAAGAAgAAAAhAEswtnpzAQAA9QIAABEAAAAAAAAAAAAAAAAArEYAAGRvY1Byb3BzL2NvcmUueG1sUEsBAi0AFAAGAAgAAAAhAJuL7VUpCwAAq3IAAA8AAAAAAAAAAAAAAAAAVkkAAHdvcmQvc3R5bGVzLnhtbFBLAQItABQABgAIAAAAIQAbH40FaQEAALcCAAAQAAAAAAAAAAAAAAAAAKxUAABkb2NQcm9wcy9hcHAueG1sUEsFBgAAAAAMAAwABgMAAEtXAAAAAA==');
  attachment.setType("application");
  attachment.setFilename("testResume.pdf");
  attachment.setDisposition("attachment");

  var mail = new helper.Mail(from_email, subject, to_email, content);
  mail.addAttachment(attachment);

  var sg = require('sendgrid')(process.env.SENDGRID_API_KEY);
  var request = sg.emptyRequest({
    method: 'POST',
    path: '/v3/mail/send',
    body: mail.toJSON()
  });



  sg.API(request, function(error, response) {
    console.log('response statusCode', response.statusCode);
    console.log('response body', response.body);
    console.log('response headers', response.headers);
  });

}); //end getJobPostings
//.................End Put Route: modifyJobStatus in DB.......................//

// from_email = new helper.Email("test@example.com");
// to_email = new helper.Email("test@example.com");
// subject = "Sending with SendGrid is Fun";
// content = new helper.Content("text/plain", "and easy to do anywhere, even with Node.js");
// mail = new helper.Mail(from_email, subject, to_email, content);
//
// var sg = require('sendgrid')(process.env.SENDGRID_API_KEY);
// var request = sg.emptyRequest({
//   method: 'POST',
//   path: '/v3/mail/send',
//   body: mail.toJSON()
// });
//
// sg.API(request, function(error, response) {
//   console.log(response.statusCode);
//   console.log(response.body);
//   console.log(response.headers);
// });



//////////////////////////////generic app.get///////////////////////////////////
app.get("/*", function(req,res){
    var file = req.params[0] || "/views/index.html";
    res.sendFile(path.join(__dirname, "../public/", file));
});
//......................End: generic app.get..................................//
